export const REGISTERING = 'REGISTERING';
export const REGISTERED = 'REGISTERED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';