export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTERING = 'REGISTERING';
export const REGISTERED = 'REGISTERED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT'; 
export const LOGOUT_FAILED = 'LOGOUT_FAILED'; 

